INSERT INTO TODO_LIST (USER_ID, TITLE, DESCRIPTION, LAST_MODIFIED_DATE) VALUES ('User1', 'Todo1', 'Description1 of user1.', CURRENT_TIMESTAMP());
INSERT INTO TODO_LIST (USER_ID, TITLE, DESCRIPTION, LAST_MODIFIED_DATE) VALUES ('User1', 'Todo2', 'Description2 of user1.', CURRENT_TIMESTAMP());
INSERT INTO TODO_LIST (USER_ID, TITLE, DESCRIPTION, LAST_MODIFIED_DATE) VALUES ('User1', 'Todo3', 'Description3 of user1.', CURRENT_TIMESTAMP());
INSERT INTO TODO_LIST (USER_ID, TITLE, DESCRIPTION, LAST_MODIFIED_DATE) VALUES ('User2', 'Todo1', 'Description1 of user2.', CURRENT_TIMESTAMP());
INSERT INTO TODO_LIST (USER_ID, TITLE, DESCRIPTION, LAST_MODIFIED_DATE) VALUES ('User2', 'Todo2', 'Description2 of user2.', CURRENT_TIMESTAMP());;