CREATE TABLE TODO_LIST (
    id   INTEGER  NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(128) NOT NULL,
    TITLE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(128) NOT NULL,
    LAST_MODIFIED_DATE DATE,
    PRIMARY KEY (id)
);